title: Esther Brown
logo: /assets/img/logo.png
email: estherbrown [at] g [dot] harvard [dot] edu
show_downloads: false
show_links: true
google_analytics: G-HNC6SH7ZSB
google_scholar: https://scholar.google.com/citations?user=NSb27XUAAAAJ&hl=en
linkedin: 
github: https://github.com/estherbrown1
theme: jekyll-theme-minimal
